version: '3.9'

networks:
    Docker_Net:
      name: Docker_Net
      external: true
      driver: macvlan
      driver_opts:
        parent: "Interface"
      ipam:
        config:
           - subnet: Docker_Subnet
             gateway: Docker_Gateway

services:

  db-postgresql15:    
    hostname: db-postgresql15
    container_name: postgresql15
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      Docker_Net:
        ipv4_address: Postgresql_IP

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'USERNAME_EMAIL'
      PGADMIN_DEFAULT_PASSWORD: 'PASSWORD'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      WEBSERVER_AUTO_CREATE_USER: 'true'
      WEBSERVER_REMOTE_USER: 'REMOTE_USER'
      AUTHENTICATION_SOURCES: 'webserver'
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin:rw
    ports:
      - "80:80"
    networks:
      Docker_Net:
        ipv4_address: PGADMIN_IP
